# 1.
include: 'rules/preprocess_reads.smk'
# 2.
include: 'rules/create_assemblies.smk'
# 3.
include: 'rules/cell_enriched_vcontig_identification.smk'
# 3.
include: 'rules/cell_enriched_vcontig_reads.smk'
#4.
include: 'rules/virus_enriched_votu_identification.smk'