# 1.
include: 'rules/elaine_preprocess_reads.smk'
# 2.
include: 'rules/elaine_create_assemblies.smk'
# 3.
include: 'rules/elaine_cell_enriched_vcontig_identification.smk'
# 3.
include: 'rules/elaine_cell_enriched_vcontig_reads.smk'
#4.
include: 'rules/elaine_virus_enriched_votu_identification.smk'