ROOT: "."
Samples:
    control:
        cell:
            day0-DO-0-env:
                - "none"
        virus:
            day0-DO-0-env:
                - "none"
    enriched:
        cell:
            day7-DO-0-12C: 
                - "1-6"
                - "7"
                - "8"
                - "9"
                - "10-12"
            day7-DO-0-13C: 
                - "1-5"
                - "6"
                - "7"
                - "8"
                - "9-12"
        virus:
            day7-DO-0-12C:
                - "1-6"
                - "7"
                - "8"
                - "9"
                - "10-12"
            day7-DO-0-13C:
                - "1-6"
                - "7"
                - "8"
                - "9"
                - "10-12"
#Log file pathway
logs: "/projects/luo_lab/Siders_data/data/logs/"


#Data processing pathways
temp_files: "/projects/luo_lab/Siders_data/data/temp_files/"

raw_reads: "/projects/luo_lab/Siders_data/data/raw/"

clean_reads: "/projects/luo_lab/Siders_data/data/processed/reads/"

assemblies: "/projects/luo_lab/Siders_data/data/processed/Assemblies/"

quality_checks: "/projects/luo_lab/Siders_data/data/processed/quailty_checks/"


# Program pathways that are needed
bbduk: "/projects/luo_lab/bbmap/"

adapters: "/projects/luo_lab/bbmap/resources/"

reference: "/projects/luo_lab/bbmap/resources/"